### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rohanvaghani** [philnash/twilio-video-react-hooks#12]
<img width="487" alt="Screen Shot 2020-03-25 at 2 04 25 PM" src="https://user-images.githubusercontent.com/35268311/77570337-ff493800-6ea1-11ea-9c48-6b69828e9a35.png">

When I enter name and room name on click I am getting this error

**Comment by rohanvaghani** [comment]
Found a solution

**Comment by manishprajapatidev** [comment]
@rohanvaghani What was the solution? please share
