### ISSUE TITLE
Will it work if we try to integrate this app into an existing serverless(react and firebase) react app?

### ISSUE THREAD

**Issue by souravdewett** [philnash/twilio-video-react-hooks#13]
How can we deploy it on netlify or heroku?

**Comment by philnash** [comment]
What you need for this app to work is an endpoint that can [return a Twilio Video Access Token](https://www.twilio.com/docs/iam/access-tokens?code-sample=code-creating-an-access-token-video-2&code-language=Node.js&code-sdk-version=3.x). In this application that is handled by [the Express server](https://github.com/philnash/twilio-video-react-hooks/blob/master/server/index.js) but that could certainly be done on Firebase or Netlify Functions or Heroku. Then the front end needs to know where that endpoint is when [it asks for the token here](https://github.com/philnash/twilio-video-react-hooks/blob/master/src/VideoChat.js#L21).

Does that help?

**Comment by souravdewett** [comment]
I tried deploying it on heroku it gives me me a page where it says "invalid host header".

**Comment by souravdewett** [comment]
@philnash can you please help me deploy it on heroku? It's really important for me.

**Comment by philnash** [comment]
So, this isn't set up particularly well for deploy to heroku right now. I'm going to spike a branch that should make it easier though, will let you know how that goes.

**Comment by philnash** [comment]
I have made the changes that this would need and tried a test deploy to Heroku successful. [Check out the changes I made here](https://github.com/philnash/twilio-video-react-hooks/compare/deploy-to-heroku).

Check out the [instructions for deploying to Heroku here](https://github.com/philnash/twilio-video-react-hooks/tree/deploy-to-heroku#deploying-this-application-to-heroku).

Let me know if that helps and I will merge the branch into master.

**Comment by souravdewett** [comment]
Worked like a charm. Thank you very much. You are a life saver.

**Comment by philnash** [comment]
Glad to hear that worked for you. I guess you are developing an application with this? Can you share what you are building? Drop me an email me at philnash [at] twilio [dot] com, I'd love to know what you are using Twilio Video for.

Thanks!
