### ISSUE TITLE
How can i create a button that toggles camera and mic off/on? 

### ISSUE THREAD

**Issue by Phyxable** [philnash/twilio-video-react-hooks#16]
I want two dedicated buttons. one for camera and one for mic. if they click on camera once, it turns on and if they click again it goes off. Same thing for the mic. I would really appreciate the help.

**Comment by philnash** [comment]
@Phyxable To toggle a camera or microphone for the local participant you can use the `enable` and `disable` methods on the [`LocalAudioTrack`](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/LocalAudioTrack.html) or [`LocalVideoTrack`](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/LocalVideoTrack.html).

To handle that on the other participants' side you'll need to listen for the [`trackEnabled` and `trackDisabled` events](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/RemoteParticipant.html#event:trackDisabled__anchor) on the participant object.

[There has been a PR to bring this to this repo](https://github.com/philnash/twilio-video-react-hooks/pull/15), but I haven't had the opportunity to review it just yet.

**Comment by Phyxable** [comment]
Thank you that PR helped.
