### ISSUE TITLE
track when remote participant enable/disable video

### ISSUE THREAD

**Issue by MilanRgm** [philnash/twilio-video-react-hooks#17]
Is there a way in twilio to track when other participant enable/disable video? When other participant(remote) disables video, the black screen is shown but if i could listen when remote participant disables video then I want to show avatar otherwise his/her video.

**Comment by philnash** [comment]
Yep, you are looking for the [`RemoteParticipant`'s `trackDisabled` and `trackEnabled` events](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/RemoteParticipant.html#event:trackDisabled__anchor).

**Comment by MilanRgm** [comment]
Thank you very much.  The below code made possible on what I wanted.

```javascript
const trackEnabled = track => {
      console.log("#######TRACK ENABLED########", track);
      if (track.kind === "video") {
        setLocalVideoTrack(track.isEnabled);
        setRemoteVideoTrack(track.isTrackEnabled);
      }
      if (track.kind === "audio") {
        setLocalAudioTrack(track.isEnabled);
        setRemoteAudioTrack(track.isTrackEnabled);
      }
    };

participant.on("trackEnabled", trackEnabled);
participant.on("trackDisabled", trackDisabled);

```
