### ISSUE TITLE
How to deploy it on AWS elastic beanstalk?

### ISSUE THREAD

**Issue by souravdewett** [philnash/twilio-video-react-hooks#18]
I tried deploying it there but getting an error that says 'Cannot Get /'.

**Comment by philnash** [comment]
I have never used AWS elastic beanstalk so I don't really know. However, this project is not entirely well set up for deployment right now.

I did make a bunch of changes in a branch that made this deployable to Heroku, but you'd probably want to make a lot of them for another platform too (especially moving the dependencies from `devDependencies` to `dependencies`). Check out the changes here: https://github.com/philnash/twilio-video-react-hooks/compare/deploy-to-heroku

Perhaps you can describe what you did to deploy and I can make some suggestions?

**Comment by souravdewett** [comment]
What i did was i moved all the dev dependencies to "dependencies". But when i deploy it it gives me a page that says 'Cannot Get /'. Other than that if i go to video/token, it is generating a token but for some reason not showing the main page where you enter a room name. I check its log which gives me an error that says 
```
h: run-p: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-express-starter@0.1.0 dev: `run-p server start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-express-starter@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Please let me know what do i need to change.

**Comment by philnash** [comment]
Ok, so you're still trying to run the application with `npm run dev` it seems. That's the command for running in development and does live reloading for the React app, so you don't want to run it like that in production.

Instead, you need to build the front-end application with the command `npm run build`. In my deploy branch I included a [line to host the static directory `./build` from the Express application](https://github.com/philnash/twilio-video-react-hooks/compare/deploy-to-heroku#diff-0861d6d6b50d7d695344bf2d86d6e5e6R12).

Once you've built the front-end, you only need to start the back-end and you can do that with `npm run server:prod`. If you need to select the port on which to run the application, provide that with an environment variable like `PORT=8080 npm run server:prod`.

Let me know if that helps.

**Comment by souravdewett** [comment]
So i set the command to `npm run server:prod`. and i also built the front end using `npm run build`. But now it gives me the error that 
```
react-express-starter@0.1.0 server /var/app/current
> node-env-run server --exec nodemon | pino-colada

Error: Could not find the .env file under: "/var/app/current/.env"
    at Object.init (/var/app/current/node_modules/node-env-run/dist/lib/cli.js:74:21)
    at Object.<anonymous> (/var/app/current/node_modules/node-env-run/dist/bin/node-env-run.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by souravdewett** [comment]
Never mind i was setting the port from env file like `app.set('port', (process.env.PORT || 3000));`. I removed it then it worked but now its not loading the room.

**Comment by souravdewett** [comment]
Can you please tell me if this works over https only? Cause i have deployed it successfully. But it is giving me an error that says `getUsermedia is not supported.`

**Comment by philnash** [comment]
@souravdewett You can only get access to the user's media (camera and microphone) over HTTPS. Security in browsers is tighter for features that give access to potentially sensitive information, you can read about [how that works for `getUserMedia` on MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Encryption_based_security).

If you need an TLS certificate, you could look into generating one for free with [LetsEncrypt](https://letsencrypt.org/).

**Comment by souravdewett** [comment]
Alright thanks.
