### ISSUE TITLE
Can not hear the voice of other person

### ISSUE THREAD

**Issue by viralpatel133** [philnash/twilio-video-react-hooks#23]
I have implemented this code. While i make the video call i can not hear the voice of other person.
Can you please help me?
Thanks

**Comment by philnash** [comment]
For testing purposes, so I don't get feedback when I open the room twice, I have the audio turned off by [muting the audio element here](https://github.com/philnash/twilio-video-react-hooks/blob/master/src/Participant.js#L69). To hear the audio, you can remove that `muted` attribute.

**Comment by philnash** [comment]
Hey @viralpatel133, I’m going to close this issue as I believe I’ve given you the right answer. Let me know if you are still having trouble though.
