### ISSUE TITLE
api error in heroku

### ISSUE THREAD

**Issue by jcvidela** [philnash/twilio-video-react-hooks#25]
Following the steps of the documentation of the deploy-to-heroku branch the application does not work correctly, the only thing I had to do to make it work is to add the buildpack of create-react-app from the heroku panel, however the https requests do not work since their response is 'method not allowed'.

The only idea that occurred to me is to do 2 deploys one from the react application and another from the API... but it's not what I'm looking for, I still haven't managed to fix it any other way
![Capture](https://user-images.githubusercontent.com/42773351/83213792-6bae1500-a139-11ea-8be0-fae0aab5b920.PNG)

**Comment by philnash** [comment]
Did you also [make the changes that are present between the two branches](https://github.com/philnash/twilio-video-react-hooks/compare/deploy-to-heroku)? You need those changes to ensure you are running the Express application on Heroku and building the React application.

**Comment by jcvidela** [comment]
Yes, I have tried that and the first time it has not worked for me, maybe I am missing the Procfile, I still do not know but now it works, thanks
