### ISSUE TITLE
Can't hear audio from other person

### ISSUE THREAD

**Issue by vinceliu21** [philnash/twilio-video-react-hooks#28]
Hi, I can see the other call attendee and the other individual can see/hear me, but I can't seem to hear them. I followed the instruction here https://github.com/philnash/twilio-video-react-hooks/issues/23#issuecomment-627790996, but that did not seem to solve it.

**Comment by philnash** [comment]
The application works the same for all participants, so if they can see and hear you then you should be able to see and hear them too. Are you able to replicate this with another person or between two devices yourself?

**Comment by vinceliu21** [comment]
Sorry. Running this same application on multiple devices did not work. The situation I described is when I used this application to communicate with another attendee on a 3rd party application with an access token. The attendee on the 3rd party app side could see & hear me when I communicated through this app, but I could only see the individual from this app.

**Comment by philnash** [comment]
Ok, thanks for the clarification.

Just to confirm, have you removed the `muted` attribute from the `<audio>` element in the Participant component? What is the JSX that you're returning from the Participant component look like? Is there anything else that you have changed?

Is there anything in the logs that you can see that might help debug this too?

**Comment by vinceliu21** [comment]
Closing the issue. Saw my mistake!

**Comment by philnash** [comment]
Glad you sorted it!
