### ISSUE TITLE
Fetching '/video/call' 404 not found

### ISSUE THREAD

**Issue by cortejojicoy** [philnash/twilio-video-react-hooks#29]
Sir why I still receive this error?, thanks for kind response

**Comment by philnash** [comment]
Hey, I'm not sure why you are getting that!

There's nothing in the code that should be making a call to `/video/call`.

The path for the token should be `/video/token`.

Have you changed anything in the code?

**Comment by cortejojicoy** [comment]
hello sir thank you for response my bad I didn't notice its `/video/token` I changed it already but it display `Module not found: Error Can't resolve 'fs' `  whenever I execute `npm run dev`

**Comment by philnash** [comment]
Hey @kukuxumusu21, that is concerning. [The `fs` module is part of the Node.js standard library](https://nodejs.org/api/fs.html#fs_file_system).

Are you trying to use `fs` in front end code?

**Comment by philnash** [comment]
Hey @kukuxumusu21 are you still having trouble with this? Or shall I close the issue?

Thanks!

**Comment by philnash** [comment]
I'm going to close this for inactivity for now. Please re-open if you're still having trouble.

**Comment by HawiCaesar** [comment]
Hey @philnash , I am having this error. Not sure why...I don't see the `fs` error

I get a 404 error when clickin on submit which calls `/video/token`

<img width="1092" alt="Screenshot 2020-10-23 at 13 06 54" src="https://user-images.githubusercontent.com/6042152/96991155-b4bf9500-1530-11eb-8274-21d7263176ef.png">

**Comment by HawiCaesar** [comment]
Silly me 😅 , I had to add the server url like so `fetch("http://localhost:3001/video/token"`

And I had to add [CORS](https://expressjs.com/en/resources/middleware/cors.html) package

**Comment by philnash** [comment]
@HawiCaesar are you running the front-end and back-end of this project separately?

If you start the project with `npm run dev` then the React application, through webpack-dev-server, should proxy API requests from localhost:3000 to localhost:3001 (where the Express server is running). You shouldn't need CORS for this, or to specify a full URL.

**Comment by HawiCaesar** [comment]
@philnash I'm not running them separately. What I did was to make a new project and only have the backend code. Then I started following the tutorial.

Looking deeper into the `package.json` I missed the proxy section. I didn't look into that.

It works fine now as per the tutorial.

Thank you for pointing that out.

**Comment by philnash** [comment]
Great to hear it's working!
