### ISSUE TITLE
Can turn off video or mute sound in local participant?

### ISSUE THREAD

**Issue by dat0825** [philnash/twilio-video-react-hooks#3]
I want to turn off video or mute sound myselft and the remote participants don't show me or listen my voice. Is there any way ?
Many thanks

**Comment by philnash** [comment]
You can `disable` your tracks, which is effectively "mute" for audio and "pause" for video.

Check out the documentation for [`LocalAudioTrack#disable`](https://media.twiliocdn.com/sdk/js/video/releases/1.19.2/docs/LocalAudioTrack.html#disable__anchor) and [`LocalVideoTrack#disable`](https://media.twiliocdn.com/sdk/js/video/releases/1.19.2/docs/LocalVideoTrack.html#disable__anchor).

Let me know if that helps at all.
