### ISSUE TITLE
issue in video

### ISSUE THREAD

**Issue by nanda-mik** [philnash/twilio-video-react-hooks#33]

**Comment by philnash** [comment]
Hello! I’m going to need a little more information than that. Could you describe your issue please?

**Comment by nanda-mik** [comment]
The issue is with twillo token. As in the console it responds with invalid signature.

**Comment by philnash** [comment]
This project works for me, so if you can give me as much detail as possible that will help. Did you follow the instructions in the readme? Have you fetched all the credentials you need from the Twilio console? Have you changed the code at all? What did you run to start the project? Is there an error message that you receive? Is there anything else you can tell me about your issue that may help me help you?

**Comment by philnash** [comment]
Did you work out the problem?

**Comment by nanda-mik** [comment]
yes
