### ISSUE TITLE
Internal Sever Error.

### ISSUE THREAD

**Issue by rajkumar73443** [philnash/twilio-video-react-hooks#34]
Hi there!
 I have tried the solution which you shared with me, where we can get the token using name and room, unfortunately, it didn't work for me and I'm getting internal server 500.
http://localhost:3000/video/token
Failed to load resource: the server responded with a status of 500 (Internal Server Error).
asyncToGenerator.js
asyncToGenerator.js:6 Uncaught (in promise) SyntaxError: Unexpected token P in JSON at position 0

Can you please take a look at this and let me know the possible solution here as we are developing a product for the healthcare industry to help the patients have better connectivity with consultants in this pandemic therefore we'd like to get this issue resolved ASAP. 

Look forward to hearing back from you.

Thanks

![videochat](https://user-images.githubusercontent.com/66951064/95552859-165d0b00-0a2b-11eb-9b25-9e085fd03db8.png)

**Comment by philnash** [comment]
Hey, I believe you have reported the [same error over here](https://github.com/philnash/react-express-starter/issues/16). That project is the base of this one, so I think if we solve it there you can apply it to this project too. I'll close this issue and see you back at the react-express-starter.
