### ISSUE TITLE
Evaluating field value for Room entry?

### ISSUE THREAD

**Issue by gregarican** [philnash/twilio-video-react-hooks#38]
This is a great introduction into Twilio development. Thanks for this! Had a quick question.

So rather than publish a project like this for production use without any authentication, I added a field for an authorization code (i.e. - the authCode text box I added). So that a user could only create/join a room if they had provided the correct credentials. I'm having trouble incorporating this into the sample project.

Here is my logic for evaluating the field value:

```javascript
function IsAuthCodeValid() {
	var hashedAuthCode = roomName.split('').reduce((prevHash, currVal) =>
                (((prevHash << 5) - prevHash) + currVal.charCodeAt(0)) | 0, 0).toString();
	if (authCode === hashedAuthCode) {		
		alert("The room's auth code to enter is: " + hashedAuthCode);
		return true;
	}
	else {
		return false;
	}
  };
```

I see when submitting the lobby entry form, the {handleSubmit} is invoked. But I can't conditionally evaluate the authCode's field value in order to fire this off. Any suggestions? I am painfully a newbie to React Hooks, so any pointers would be appreciated!

**Comment by philnash** [comment]
Hey @gregarican, interesting question. It looks like you are generating the auth code from the room name itself, which doesn't seem like the most secure way to protect something, especially if this code is part of the front-end code and can be read by anyone visiting the site.

Still, here's a few ideas for what you can do.

To stick with your function and perform the auth code validation in the Lobby component you would need to add an input to the Lobby, keep the auth code updated with a state hook and then intercept the handleSubmit function. Something like this might work:

```javascript
import React, { useState, useCallback } from 'react';

const Lobby = ({
  username,
  handleUsernameChange,
  roomName,
  handleRoomNameChange,
  handleSubmit
}) => {
  const [authCode, setAuthCode] = useState("");
  const handleAuthCodeChange = useCallback((event) => {
    setAuthCode(event.target.value);
  }, []);
  const isAuthCodeValid = () => {
    hashedAuthCode = roomName.split('').reduce((prevHash, currVal) =>
      (((prevHash << 5) - prevHash) + currVal.charCodeAt(0)) | 0, 0).toString();
    if (authCode === hashedAuthCode) {		
      alert("The room's auth code to enter is: " + hashedAuthCode);
      return true;
    } else {
      return false;
    }
  }
  const handleSubmitWithAuthCodeGuard = useCallback(event => {
    event.preventDefault();
    if (isAuthCodeValid()) {
      handleSubmit(event);
    } else {
      // Do something to show an error to the user
    }
  }, []);

  return (
    <form onSubmit={handleSubmitWithAuthCodeGuard}>
      <h2>Enter a room</h2>
      <div>
        <label htmlFor="name">Name:</label>
        <input
          type="text"
          id="field"
          value={username}
          onChange={handleUsernameChange}
          required
        />
      </div>

      <div>
        <label htmlFor="room">Room name:</label>
        <input
          type="text"
          id="room"
          value={roomName}
          onChange={handleRoomNameChange}
          required
        />
      </div>


      <div>
        <label htmlFor="authCode">Auth Code:</label>
        <input
          type="text"
          id="authCode"
          value={authCode}
          onChange={handleAuthCodeChange}
          required
        />
      </div>

      <button type="submit">Submit</button>
    </form>
  );
};

export default Lobby;
```

But like I said, that is not super secure.

I would prefer your auth code, however it is generated, was checked on the server side. For that you would add the `authCode` input as above, but handle the state and change events in the `VideoChat` component the same way as for the `roomName` and `name`. Then, in `handleSubmit` send the `authCode` to the server side along with the `name` and `roomName`

```javascript
  const handleSubmit = useCallback(
    async event => {
      event.preventDefault();
      const data = await fetch('/video/token', {
        method: 'POST',
        body: JSON.stringify({
          identity: username,
          room: roomName,
          authCode: authCode
        }),
        headers: {
          'Content-Type': 'application/json'
        }
      }).then(res => {
        if (res.ok) {
          return res.json();
        } else {
          // Handle incorrect auth code.
        }
      });
      setToken(data.token);
    },
    [roomName, username, authCode]
  );
```

Then on the server side, only return an access token if the auth code is correct. Something like this:

```javascript
app.post('/video/token', (req, res) => {
  const identity = req.body.identity;
  const room = req.body.room;
  const authCode = req.body.authCode;
  if (isAuthCodeValid(authCode)) {
    const token = videoToken(identity, room, config);
    sendTokenResponse(token, res);
  } else {
    res.status(401).json({ authorised: false });
  } 
});
```

Let me know if that helps at all.

**Comment by gregarican** [comment]
Thanks so much for the insight! The server-side option makes more sense for production purposes. I was just trying to initially mock something up. And your recommendations and sample code should work out great. Coming primarily from the world of C# and ASP.NET type of development I am still trying to learn React. And this project is a great starting point for me. Thanks again!

**Comment by gregarican** [comment]
As this was a question, and not an issue with the project itself, closing this. My updated code works fine. Placed most all of the underlying logic in the index.js and VideoChat.js, to help hide the mechanisms from the user. Works great. Appreciate the point in the right direction! :)

**Comment by philnash** [comment]
Glad to hear this helped and thanks for following up!
