### ISSUE TITLE
Camera selection?

### ISSUE THREAD

**Issue by gregarican** [philnash/twilio-video-react-hooks#39]
One feature that would be interesting would be allowing the app user to select which camera to use for their session. In the event there are multiple cameras. I assume that the default camera is automatically assigned to the session. Out of curiosity, how much work would be required to add this feature? What would be a good starting-off point for me to start coding this?

**Comment by gregarican** [comment]
I did see your other project (https://github.com/philnash/mediadevices-camera-selection) and am attempting to port this over for React/Hooks.

**Comment by gregarican** [comment]
Please disregard, I was able to cobble it together :)

**Comment by philnash** [comment]
Glad to see you found my other repo and you got the feature working here.
