### ISSUE TITLE
overlay remote participants on the local participants

### ISSUE THREAD

**Issue by sowsan** [philnash/twilio-video-react-hooks#46]
Is there a sample/reference on how to make this sample to render video with a view something like below? I was looking at your blog on overlay https://www.twilio.com/blog/add-an-overlay-to-web-video-chat , is there a sample for overlay remote participants on the local participant? 

![image](https://user-images.githubusercontent.com/11544153/109449466-84c05b00-7a16-11eb-9562-1ef37a871051.png)

**Comment by philnash** [comment]
There isn't a sample based on that, but the theory behind the overlay blog post is the same. Position the container of the videos relatively, then position the overlay video absolutely.

**Comment by sowsan** [comment]
Thank you, @philnash
