### ISSUE TITLE
The authorization with Token failed

### ISSUE THREAD

**Issue by AmanSonii** [philnash/twilio-video-react-hooks#7]
Hii,
 
I registered on Twilio console successfully and got the API key with API secret and wrote all the information in the .env file. But when I tried to join the room it showed me 
**'The authorization with Token failed'**
I have a trial account do I need to upgrade the account?

**Comment by philnash** [comment]
You shouldn't need to upgrade the account to test out Video.

Have you changed anything in the code?

Also, can you run this [WebRTC test](https://networktest.twilio.com/) just to confirm your browser/network will work with Twilio Video.

**Comment by philnash** [comment]
Hi @AmanSonii,

Did you get any further with this? Have you got your token to work yet?

**Comment by cmpscabral** [comment]
Hi Phil,
I'm testing your app and I can't get pass the token issue also.

I created an API key and secret, created the .env file.
When joining a room I get "404 page not found" when requesting "/video/token"

Should I create a token in my console (manually or via REST api) and make it available at this location?

Can you tell me what's missing?

Thank you!

**Comment by cmpscabral** [comment]
Please disregard my previous comment (https://github.com/philnash/twilio-video-react-hooks/issues/7#issuecomment-601752011)

I'm trying this locally now and it works (both on localhost and via ssl proxy) so I must be doing something else wrong...

**Comment by philnash** [comment]
@cmpscabral If it is working locally and via proxy, where is it failing?

**Comment by cmpscabral** [comment]
I tried your code in a brand new Linode VM, with ubuntu 18.04 and followed all the steps.
Locally I tried it in a OSX

**Comment by philnash** [comment]
So, this repo doesn't really come with instructions for deployment. Which should include building the React app into a production build and running the Express application separately. In the current state, it is not ready for that, and since there are so many ways to deploy, I didn't want to have too many opinions over it. (One mistake I've made is to put the server side dependencies into `devDependencies`, that's not going to go well in production!)

Let me know how I can help guide you here.

**Comment by Phyxable** [comment]
<img width="487" alt="Screen Shot 2020-03-25 at 2 04 25 PM" src="https://user-images.githubusercontent.com/43259050/77570078-9cf03780-6ea1-11ea-8168-6698c812811f.png">

**Comment by rohanvaghani** [comment]
<img width="487" alt="Screen Shot 2020-03-25 at 2 04 25 PM" src="https://user-images.githubusercontent.com/35268311/77570192-bc876000-6ea1-11ea-8d38-03cb9ab94d55.png">

**Comment by AmanSonii** [comment]
> Hi @AmanSonii,
> 
> Did you get any further with this? Have you got your token to work yet?

Thanks for your kind response. I didn't work on that.

**Comment by philnash** [comment]
Hi @AmanSonii, thanks for your response. Is this issue done with then? Can it be closed or will you be returning to work on it again?

**Comment by philnash** [comment]
I am going to close this issue, but do open it up again if you need more help.

**Comment by cmpscabral** [comment]
@philnash Hi Phil, sorry for not replying sooner.

I went with VueJS instead, borrowed some concepts from your project and from the quickstart and eventually made it work.

Thanks again!
