### ISSUE TITLE
Camera won't disconnect

### ISSUE THREAD

**Issue by mauerv** [philnash/twilio-video-react-hooks#8]
Hi, I'm trying the code as is, and everything works correctly except one thing. If I join a room, and then leave, the camera doesn't disconnect. The icon keeps blinking in my tab and chrome lets me know that the app is still using my video. I tried building a small app of my own and the same thing happens, I'm wondering if it's a bug with twilio-video?

**Comment by mauerv** [comment]
I just found one of your answers in stackoverflow that helped me solve the problem. Adding track.stop() seems to fix it: https://stackoverflow.com/questions/45363228/disconnect-twilio-video

**Comment by philnash** [comment]
Ah, you're right, apologies for this.

I've updated the repo with these three lines in `src/Room.js`:

https://github.com/philnash/twilio-video-react-hooks/blob/8e4140becc3ed83f8584e2a6cc5640d1002efc9b/src/Room.js#L32-L34

That seemed to work for me. Thanks for reporting!
