### ISSUE TITLE
Problem in receive audio

### ISSUE THREAD

**Issue by devAmirHemmati** [philnash/twilio-video-react-hooks#80]
I receive video successfully, but I don't receive audio in this app!

**Comment by philnash** [comment]
The audio is muted (it saves you from deafening yourself when testing on your own). Remove [this `muted` attribute from the `<audio>` element and you will be able to hear](https://github.com/philnash/twilio-video-react-hooks/blob/77049988925e1e6d20425043c0a605d893f7ae80/src/Participant.js#L69).
